<?php

namespace Container26UbxeT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_IjwxerxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Ijwxerx' shared service.
     *
     * @return \App\Controller\equest
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\MessageController::removeParticipantFromConversation()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\equest". Did you forget to add a use statement?');
    }
}
