<?php

namespace ContainerLRlpudq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'ux-twig-component'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ComponentFactory.php';

        return $container->privates['ux.twig_component.component_factory'] = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LiveTestPage' => [false, 'App\\Controller\\LiveTestController', 'getLiveTestControllerService', true],
            'chat' => [false, 'App\\Controller\\MessageController', 'getMessageControllerService', true],
        ], [
            'LiveTestPage' => 'App\\Controller\\LiveTestController',
            'chat' => 'App\\Controller\\MessageController',
        ]), ($container->privates['property_accessor'] ?? $container->load('getPropertyAccessorService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ['LiveTestPage' => ['key' => 'LiveTestPage', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'service_id' => 'App\\Controller\\LiveTestController', 'class' => 'App\\Controller\\LiveTestController', 'template' => 'components/LiveTestPage.html.twig'], 'chat' => ['key' => 'chat', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'service_id' => 'App\\Controller\\MessageController', 'class' => 'App\\Controller\\MessageController', 'template' => 'components/chat.html.twig']]);
    }
}
