<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGWlDH08\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGWlDH08/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGWlDH08.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGWlDH08\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGWlDH08\App_KernelDevDebugContainer([
    'container.build_hash' => 'GWlDH08',
    'container.build_id' => '81ee4337',
    'container.build_time' => 1676641654,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGWlDH08');
