<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDBKwN8o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDBKwN8o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDBKwN8o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDBKwN8o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDBKwN8o\App_KernelDevDebugContainer([
    'container.build_hash' => 'DBKwN8o',
    'container.build_id' => '2bc0a420',
    'container.build_time' => 1676814420,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDBKwN8o');
