<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/public/build/runtime.js',
                '/public/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_symfony_ux-live-compo-9da9ca.js',
                '/public/build/app.js',
            ],
            'css' => [
                '/public/build/app.css',
            ],
        ],
        'admin' => [
            'js' => [
                '/public/build/runtime.js',
            ],
            'css' => [
                '/public/build/admin.css',
            ],
        ],
    ],
],

]];
